[package]
name        = "interop-base"
description = "Low level Flix wrappers over classes and interfaces in the JDK"
version     = "0.3.1"
flix        = "0.36.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

